### ISSUE TITLE
Headings needs to be checked for symbols

### ISSUE THREAD

**Issue by SJellen** [my-covid-story/www#143] opened 2021-04-28 17:36 UTC
<img width="593" alt="Screen Shot 2021-04-28 at 1 29 01 PM" src="https://user-images.githubusercontent.com/51421669/116447632-34068c00-a826-11eb-849a-a3b5a654c2e4.png">

Looks like its just in the heading and is only amp

**Comment by silent1mezzo** [comment] 2021-04-28 17:42
Thanks for bringing this up @SJellen! We're going to handle this along with content in https://github.com/my-covid-story/www/issues/137

**Comment by davesteinberg** [comment] 2021-05-03 02:14
Closing this as duplicate of #137

**Closed by davesteinberg** 2021-05-03 02:14 UTC
